name: Deploy do site "dmodesigner.com.br" em homologação

on:
  push:
    branches: [ "approval" ]
  pull_request:
    branches: [ "approval" ]

env:
  LOCAL: ${{ github.workspace }}/output/
  SERVER: "hmg.dmodesigner.com.br/"
  
jobs:
  web-deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
    
    - name: Obter a última versão do código
      uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.0.x
        
    - name: Restaura as Dependencias
      run: dotnet restore
      
    - name: Gera o Pacote
      run: dotnet publish -c Release -o ${{ env.LOCAL }}
      
    - name: Sincronizar arquivos
      uses: SamKirkland/FTP-Deploy-Action@v4.3.4      
      with:
        server: ${{ secrets.HOST_FTP }}
        username: ${{ secrets.USER_FTP }}
        password: ${{ secrets.PASSWORD_FTP }}
        local-dir: ${{ env.LOCAL }}
        server-dir: ${{ env.SERVER }}